# permissions for end users to view digitaltwins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: digitaltwin-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: plantd-operator
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
  name: digitaltwin-viewer-role
rules:
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - digitaltwins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - digitaltwins/status
  verbs:
  - get
