# permissions for end users to view experiments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: experiment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: plantd-operator
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
  name: experiment-viewer-role
rules:
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - experiments/status
  verbs:
  - get
