---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: prometheus-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: plantd-operator
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
  namespace: system
  name: prometheus
