---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - k6s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - costexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - costexporters/finalizers
  verbs:
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - costexporters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - datasets/finalizers
  verbs:
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - datasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - experiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - experiments/finalizers
  verbs:
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - experiments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - loadpatterns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - plantdcores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - plantdcores/finalizers
  verbs:
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - plantdcores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - windtunnel.plantd.org
  resources:
  - schemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
