apiVersion: windtunnel.plantd.org/v1alpha1
kind: CostExporter
metadata:
  labels:
    app.kubernetes.io/name: costexporter
    app.kubernetes.io/instance: costexporter-sample
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name: costexporter-sample
spec:
  s3Bucket: cost-logging
  cloudServiceProvider: aws
  secretRef:
    name: csp-credentials
    namespace: default
