apiVersion: windtunnel.plantd.org/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
