apiVersion: windtunnel.plantd.org/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema
    app.kubernetes.io/instance: schema-sample
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name: schema-sample
spec:
  # TODO(user): Add fields here
