apiVersion: windtunnel.plantd.org/v1alpha1
kind: TrafficModel
metadata:
  labels:
    app.kubernetes.io/name: trafficmodel
    app.kubernetes.io/instance: trafficmodel-sample
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name: trafficmodel-sample
spec:
  # TODO(user): Add fields here