apiVersion: windtunnel.plantd.org/v1alpha1
kind: PlantDCore
metadata:
  labels:
    app.kubernetes.io/name: plantdcore
    app.kubernetes.io/instance: plantdcore-sample
    app.kubernetes.io/part-of: plantd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd-operator
  name: plantdcore-sample
spec:
  # TODO(user): Add fields here
