apiVersion: windtunnel.plantd.org/v1alpha1
kind: DigitalTwin
metadata:
  namespace: test-pipeline
  name: digitaltwin-incluster
spec:
  modelType: quickscaling
  experiments:
    - namespace: test-pipeline
      name: experiment-test-pipeline
