name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22.0'

      - name: Go Mod Download
        run: go mod download

      - name: Go Mod Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Format
        run: go fmt ./... && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Test
        run: go test ./...

      - name: Go Build Controller Manager
        run: go build -o /dev/null ./cmd/main.go

      - name: Go Build Data Generator
        run: go build -o /dev/null ./apps/datagen/main.go

      - name: Go Build PlantD Proxy
        run: go build -o /dev/null ./apps/plantd-proxy/main.go
